version: '3.8'

services:
  nginx:
    restart: on-failure
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - 80:80
    depends_on:
      - web
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        python manage.py collectstatic
        gunicorn country_guess.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env.prod

volumes:
  static_volume:
  media_volume: