version: '3.8'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate --noinput
        python manage.py loaddata static/country_data.json
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14.7-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 2

volumes:
  static_volume:
  media_volume:
  postgres_data: