/* tslint:disable */
/* eslint-disable */
/**
 * Country Guess API
 * Description placeholder2
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Country
 */
export interface Country {
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    capital: string;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    region: string;
    /**
     * 
     * @type {number}
     * @memberof Country
     */
    population: number;
    /**
     * 
     * @type {string}
     * @memberof Country
     */
    flag: string;
    /**
     * 
     * @type {Date}
     * @memberof Country
     */
    readonly modifiedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Country
     */
    usedAt?: Date | null;
}

/**
 * Check if a given object implements the Country interface.
 */
export function instanceOfCountry(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "capital" in value;
    isInstance = isInstance && "region" in value;
    isInstance = isInstance && "population" in value;
    isInstance = isInstance && "flag" in value;
    isInstance = isInstance && "modifiedAt" in value;

    return isInstance;
}

export function CountryFromJSON(json: any): Country {
    return CountryFromJSONTyped(json, false);
}

export function CountryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Country {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'name': json['name'],
        'capital': json['capital'],
        'region': json['region'],
        'population': json['population'],
        'flag': json['flag'],
        'modifiedAt': (new Date(json['modified_at'])),
        'usedAt': !exists(json, 'used_at') ? undefined : (json['used_at'] === null ? null : new Date(json['used_at'])),
    };
}

export function CountryToJSON(value?: Country | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'name': value.name,
        'capital': value.capital,
        'region': value.region,
        'population': value.population,
        'flag': value.flag,
        'used_at': value.usedAt === undefined ? undefined : (value.usedAt === null ? null : value.usedAt.toISOString().substr(0,10)),
    };
}

