/* tslint:disable */
/* eslint-disable */
/**
 * Country Guess API
 * Description placeholder2
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CountryExists
 */
export interface CountryExists {
    /**
     * 
     * @type {string}
     * @memberof CountryExists
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof CountryExists
     */
    _exists?: boolean;
}

/**
 * Check if a given object implements the CountryExists interface.
 */
export function instanceOfCountryExists(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CountryExistsFromJSON(json: any): CountryExists {
    return CountryExistsFromJSONTyped(json, false);
}

export function CountryExistsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountryExists {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        '_exists': !exists(json, 'exists') ? undefined : json['exists'],
    };
}

export function CountryExistsToJSON(value?: CountryExists | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'exists': value._exists,
    };
}

