/* tslint:disable */
/* eslint-disable */
/**
 * Country Guess API
 * Description placeholder2
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `succes` - succes
 * * `fail` - fail
 * * `wait` - wait
 * @export
 */
export const GameStateEnum = {
    Succes: 'succes',
    Fail: 'fail',
    Wait: 'wait'
} as const;
export type GameStateEnum = typeof GameStateEnum[keyof typeof GameStateEnum];


export function GameStateEnumFromJSON(json: any): GameStateEnum {
    return GameStateEnumFromJSONTyped(json, false);
}

export function GameStateEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameStateEnum {
    return json as GameStateEnum;
}

export function GameStateEnumToJSON(value?: GameStateEnum | null): any {
    return value as any;
}

