/* tslint:disable */
/* eslint-disable */
/**
 * Country Guess API
 * Description placeholder2
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameStateEnum } from './GameStateEnum';
import {
    GameStateEnumFromJSON,
    GameStateEnumFromJSONTyped,
    GameStateEnumToJSON,
} from './GameStateEnum';

/**
 * 
 * @export
 * @interface GameSate
 */
export interface GameSate {
    /**
     * 
     * @type {boolean}
     * @memberof GameSate
     */
    finishedToday: boolean;
    /**
     * 
     * @type {GameStateEnum}
     * @memberof GameSate
     */
    gameState: GameStateEnum;
    /**
     * 
     * @type {number}
     * @memberof GameSate
     */
    numberTries?: number;
}

/**
 * Check if a given object implements the GameSate interface.
 */
export function instanceOfGameSate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "finishedToday" in value;
    isInstance = isInstance && "gameState" in value;

    return isInstance;
}

export function GameSateFromJSON(json: any): GameSate {
    return GameSateFromJSONTyped(json, false);
}

export function GameSateFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameSate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'finishedToday': json['finished_today'],
        'gameState': GameStateEnumFromJSON(json['game_state']),
        'numberTries': !exists(json, 'number_tries') ? undefined : json['number_tries'],
    };
}

export function GameSateToJSON(value?: GameSate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'finished_today': value.finishedToday,
        'game_state': GameStateEnumToJSON(value.gameState),
        'number_tries': value.numberTries,
    };
}

