/* tslint:disable */
/* eslint-disable */
/**
 * Country Guess API
 * Description placeholder2
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Country } from './Country';
import {
    CountryFromJSON,
    CountryFromJSONTyped,
    CountryToJSON,
} from './Country';

/**
 * 
 * @export
 * @interface PaginatedCountryList
 */
export interface PaginatedCountryList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCountryList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCountryList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCountryList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Country>}
     * @memberof PaginatedCountryList
     */
    results?: Array<Country>;
}

/**
 * Check if a given object implements the PaginatedCountryList interface.
 */
export function instanceOfPaginatedCountryList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedCountryListFromJSON(json: any): PaginatedCountryList {
    return PaginatedCountryListFromJSONTyped(json, false);
}

export function PaginatedCountryListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCountryList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(CountryFromJSON)),
    };
}

export function PaginatedCountryListToJSON(value?: PaginatedCountryList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(CountryToJSON)),
    };
}

