/* tslint:disable */
/* eslint-disable */
/**
 * Country Guess API
 * Description placeholder2
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedCountry
 */
export interface PatchedCountry {
    /**
     * 
     * @type {string}
     * @memberof PatchedCountry
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCountry
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCountry
     */
    capital?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCountry
     */
    region?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedCountry
     */
    population?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedCountry
     */
    flag?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCountry
     */
    readonly modifiedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCountry
     */
    usedAt?: Date | null;
}

/**
 * Check if a given object implements the PatchedCountry interface.
 */
export function instanceOfPatchedCountry(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedCountryFromJSON(json: any): PatchedCountry {
    return PatchedCountryFromJSONTyped(json, false);
}

export function PatchedCountryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCountry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'capital': !exists(json, 'capital') ? undefined : json['capital'],
        'region': !exists(json, 'region') ? undefined : json['region'],
        'population': !exists(json, 'population') ? undefined : json['population'],
        'flag': !exists(json, 'flag') ? undefined : json['flag'],
        'modifiedAt': !exists(json, 'modified_at') ? undefined : (new Date(json['modified_at'])),
        'usedAt': !exists(json, 'used_at') ? undefined : (json['used_at'] === null ? null : new Date(json['used_at'])),
    };
}

export function PatchedCountryToJSON(value?: PatchedCountry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'name': value.name,
        'capital': value.capital,
        'region': value.region,
        'population': value.population,
        'flag': value.flag,
        'used_at': value.usedAt === undefined ? undefined : (value.usedAt === null ? null : value.usedAt.toISOString().substr(0,10)),
    };
}

