/* tslint:disable */
/* eslint-disable */
/**
 * Country Guess API
 * Description placeholder2
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `EU` - Europe
 * * `AS` - Asia
 * * `AM` - Americas
 * * `AF` - Africa
 * * `OC` - Oceania
 * * `AQ` - Antarctic
 * @export
 */
export const RegionEnum = {
    Eu: 'EU',
    As: 'AS',
    Am: 'AM',
    Af: 'AF',
    Oc: 'OC',
    Aq: 'AQ'
} as const;
export type RegionEnum = typeof RegionEnum[keyof typeof RegionEnum];


export function RegionEnumFromJSON(json: any): RegionEnum {
    return RegionEnumFromJSONTyped(json, false);
}

export function RegionEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegionEnum {
    return json as RegionEnum;
}

export function RegionEnumToJSON(value?: RegionEnum | null): any {
    return value as any;
}

