# Generated by Django 4.2.1 on 2023-06-01 09:37

import django.core.validators
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('capital', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('EU', 'Europe'), ('AS', 'Asia'), ('AM', 'Americas'), ('AF', 'Africa'), ('OC', 'Oceania'), ('AQ', 'Antarctic')], max_length=200)),
                ('population', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('flag', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='flag_images')),
                ('ppoi', versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
